### ISSUE TITLE
Discussion - multiple independent random trackers

### ISSUE THREAD

**Issue by greg-kennedy** [catseye/seedbank#2]

**Comment by greg-kennedy** [comment]
Uh whoops

**Comment by cpressey** [comment]
Probably outside the scope of this little project to support that, but... it looks like you could do something like this at the start of the program to create several independent generators all based on the seed chosen by seedbank:

```
generators = []
for x in xrange(0, 5):
    g = random.Random()
    g.setstate(random.getstate())
    generators.append(g)
    random.jumpahead()
```

Note that this is completely untested... I'm basically guessing based on what [the docs](https://docs.python.org/2/library/random.html) say.
