### ISSUE TITLE
Unlicense doesn't do a good job of putting stuff in the public domain; I suggest switching to CC0

### ISSUE THREAD

**Issue by pointyointment** [catseye/seedbank#3]
[Here is why the Unlicense doesn't work well and is even illegal in some countries.](http://programmers.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense) ([archive of linked mailing list message](https://wayback.archive.org/web/20150907225139/https://lists.opensource.org/pipermail/license-review/2012-January/000052.html))

CC0 was written by actual lawyers who knew what they were doing, and doesn't have those problems.

**Comment by cpressey** [comment]
No thanks.

**Comment by pointyointment** [comment]
Very well. I'll write my own if I ever want seed management in the future.

**Comment by pointyointment** [comment]
@cpressey, I would like to clarify that my decision is not because I have any dislike for you or your code, but only because I consider your chosen public domain dedication invalid, leaving the legality of reusing your code uncertain.
